### ISSUE TITLE
Is there a problem with the kprobe of the kernel? Compiling kernelsu failed to start, link: https://kernelsu.org ， https://github.com/tiann/KernelSU

### ISSUE THREAD

**Issue by leezn** [baalgx/kernel_xiaomi_cepheus#1]

**Comment by balgxmr** [comment]
Hi, for now i don't have plans on kernelSU stuff, i will not check it yet, but you may want to check soviet-android repo, dev/ksu branch

https://github.com/SOVIET-ANDROID/kernel_xiaomi_raphael/tree/dev/KSU
